#!/usr/bin/env perl
#
# jamirdochegal  -  listen to web radios via mplayer
# Copyright (C) 2009-2022  Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL v2 (or later)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;

use IPC::Cmd qw(can_run);

use constant PLAYERS => (
    { BINARY => 'mplayer', PARAMS => [ '-cache', '256' ] },
    { BINARY => 'mpv', PARAMS => [ '--cache-secs=10' ] }
    );

#### process a line from the stations list
my %station;
sub process_station_line($)
{
    my $line = shift;

    chomp $line;
    return if $line =~ /^\s*$/;
    return if $line =~ /^\s*#/;

    if ($line =~ /^\s*DELETE:(\S+)\s*$/) {
	return "can't delete unkown station `$1'" unless exists $station{$1};
	delete $station{$1};

    } elsif ($line =~ /^\s*RENAME:(\S+)\s(\S+)*$/) {
	return "can't rename unkown station `$1'" unless exists $station{$1};
	$station{$2} = $station{$1};
	$station{$2}->{'SHORTCUT'} = $2;
	delete $station{$1};

    } elsif ($line =~ /^(?:\s*(\S+)\|)?(.*)\s+(\S+)\s*$/) {
	my ($shortcut, $name, $url, $flags) = ($1, $2, $3, {});

	$shortcut = $name unless defined $shortcut;

	while ($url =~ s/^([A-Z]+)://g) {
	    $flags->{$1}++;
	}

	$station{$shortcut} = {
	    'SHORTCUT' => $shortcut,
	    'NAME'     => $name,
	    'URL'      => $url,
	    'FLAGS'    => $flags,
	};

    } else {
	return "broken line";
    }
    return "";
}

#### check if a given player exists
sub player_exists($)
{
    return can_run( $_->{BINARY} );
}

#### get URL for station: either use direct URL or try to parse playlist
sub get_url($)
{
    my ($station) = @_;

    my $url = $station->{URL};
    if (exists ($station->{FLAGS}->{DIRECT})) {
	return $url;
    }

    # this is totally simple & stupid but mplayer discouraged using their -playlist option
    my @found = ();
    open my $playlist, '-|', "curl -s \"$url\"" or die "can't open curl for $url: $!\n";
    while (my $line = <$playlist>) {
	if ($line =~ m,(https?://\S+),) {
	    my $found = $1;
	    $found =~ s,["].*,,;
	    push @found, $found;
	}
    }
    close $playlist or die "can't close curl for $url: $!\n";

    return @found[ int(rand(scalar @found)) ];
}

#### read global stations
while (my $line = <DATA>) {
    my $err = process_station_line($line);
    warn "global configuration [$.]: $err\n" if $err;
}


#### read local stations
my $rcfile = $ENV{HOME}.'/.jamirdochegalrc';
if ( -e $rcfile ) {
    open RCFILE, '<', $rcfile or warn "can't open `$rcfile': $!\n";
    while (my $line = <RCFILE>) {
	my $err = process_station_line($line);
	warn "local configuration [$.]: $err\n" if $err;
    }
    close RCFILE or warn "can't open `$rcfile': $!\n";
}


#### default action
if (@ARGV == 0) {
    unshift @ARGV, '-r';
}


#### read flags
my ($do_help, $do_list, $do_random) = (0, 0, 0);
while (@ARGV) {
    if ($ARGV[0] eq '-h') {
	$do_help = 1;
	shift @ARGV;
    } elsif ($ARGV[0] eq '-l') {
	$do_list = 1;
	shift @ARGV;
    } elsif ($ARGV[0] eq '-r') {
	$do_random = 1;
	shift @ARGV;
    } else {
	last;
    }
}


#### print help?
if ($do_help) {
    print << "EOF" ;

jamirdochegal  -  listen to web radios via mplayer
Copyright (C) 2009-2016,2019  Christian Garbs <mitch\@cgarbs.de>
Licensed under GNU GPL v2 (or later)

usage:
  jamirdochegal
  jamirdochegal -h
  jamirdochegal [-l|-r] <station> [<additional-mplayer-arguments>]

  -h   print this help
  -l   list stations
  -r   tune into a random station (default with no arguments given)

EOF
    ; ## FIXME: mention ~/.jamirdochegalrc
    exit 0;
}


#### filter station list
my @matches;
my $filter;
if (@ARGV) {
    $filter = shift @ARGV;
    if (exists $station{$filter}) {
	# exact match
	@matches = ( $filter );
    } else {
	# match on short names
	@matches = grep { substr($_, 0, length $filter) eq $filter } keys %station;
	if (@matches == 0) {
	    # fallback: try full-text search on long station names
	    @matches = grep { index($station{$_}->{'NAME'}, $filter) >= 0 } keys %station;
	}
    }
} else {
    $filter = '';
    @matches = keys %station;
}
@matches = sort @matches;


#### print station list?
if ($do_list) {
    foreach my $station (@matches) {
	if ($station eq $station{$station}->{'NAME'}) {
	    print "$station\n";
	} else {
	    print "$station  ($station{$station}->{'NAME'})\n";
	}
    }
    exit 0;
}


#### random station?
if ($do_random) {
    @matches = (@matches[ int rand (@matches) ]);
}


#### tune in
if (@matches == 0) {
    die "unknown station `$filter'\n";
} elsif (@matches > 1) {
    warn "inexact station name `$filter'\n";
    warn "possible completions:\n";
    foreach my $station (@matches) {  ## FIXME: duplicate code; extract method list_stations
	if ($station eq $station{$station}->{'NAME'}) {
	    print "$station\n";
	} else {
	    print "$station  ($station{$station}->{'NAME'})\n";
	}
    }
    exit 0;
}
my $selected_station = $station{$matches[0]};
print "\n>>>> $selected_station->{NAME}\n\n";
my @parms;
push @parms, ('-demuxer', 'ogg') if exists $selected_station->{FLAGS}->{OGGDEMUX};


#### find player to use
my @available_players = grep { player_exists($_) } PLAYERS;
die 'no suitable player found' unless @available_players;
my $player = $available_players[-1];


#### and play
exec $player->{BINARY}, @{$player->{PARAMS}}, @parms, get_url($selected_station), @ARGV;


#### the station list
# - define stations:
#   [<shortcut>|]<name> [<flag>]<url>
#   where <url> is a playlist
#   <flag> is optional an can be one or more of:
#   DIRECT:    when <url> is no playlist but a direct stream
#   OGGDEMUX:  work around mplayer/lavf-demuxer problems with OGG streams
# - delete stations:
#   DELETE:<name>
#   DELETE:<shortcut>
# - rename stations:
#   RENAME:<name> <shortcut>
#   RENAME:<shortcut> <shortcut>
__DATA__
aby-antenne|ANTENNE BAYERN Live DIRECT:https://stream.antenne.de/antenne/stream/aacp
aby-2000er-hits|ANTENNE BAYERN 2000er Hits DIRECT:https://stream.antenne.de/2000er-hits/stream/aacp
aby-2010er-hits|ANTENNE BAYERN 2010er Hits DIRECT:https://stream.antenne.de/2010er-hits/stream/aacp
aby-70er-hits|ANTENNE BAYERN 70er Hits DIRECT:https://stream.antenne.de/70er-hits/stream/aacp
aby-antenne-bayern-70er-rock|ANTENNE BAYERN 70er Rock DIRECT:https://stream.antenne.de/antenne-bayern-70er-rock/stream/aacp
aby-antenne-bayern-80er-disco-hits|ANTENNE BAYERN 80er Disco Hits DIRECT:https://stream.antenne.de/antenne-bayern-80er-disco-hits/stream/aacp
aby-80er-kulthits|ANTENNE BAYERN 80er Hits DIRECT:https://stream.antenne.de/80er-kulthits/stream/aacp
aby-antenne-bayern-80er-party|ANTENNE BAYERN 80er Party DIRECT:https://stream.antenne.de/antenne-bayern-80er-party/stream/aacp
aby-antenne-bayern-80er-rock|ANTENNE BAYERN 80er Rock DIRECT:https://stream.antenne.de/antenne-bayern-80er-rock/stream/aacp
aby-antenne-bayern-90er-eurodance|ANTENNE BAYERN 90er Eurodance DIRECT:https://stream.antenne.de/antenne-bayern-90er-eurodance/stream/aacp
aby-90er-hits|ANTENNE BAYERN 90er Hits DIRECT:https://stream.antenne.de/90er-hits/stream/aacp
aby-antenne-bayern-90er-party|ANTENNE BAYERN 90er Party DIRECT:https://stream.antenne.de/antenne-bayern-90er-party/stream/aacp
aby-antenne-bayern-90er-rock|ANTENNE BAYERN 90er Rock DIRECT:https://stream.antenne.de/antenne-bayern-90er-rock/stream/aacp
aby-apres-ski|ANTENNE BAYERN Après Ski DIRECT:https://stream.antenne.de/apres-ski/stream/aacp
aby-bayerische-weihnacht|ANTENNE BAYERN Bayerische Weihnacht DIRECT:https://stream.antenne.de/bayerische-weihnacht/stream/aacp
aby-bayern-sound|ANTENNE BAYERN Bayern Sound DIRECT:https://stream.antenne.de/bayern-sound/stream/aacp
aby-black-beatz|ANTENNE BAYERN Black Music DIRECT:https://stream.antenne.de/black-beatz/stream/aacp
aby-chillout|ANTENNE BAYERN CHILLOUT ANTENNE DIRECT:https://stream.antenne.de/chillout/stream/aacp
aby-country-antenne|ANTENNE BAYERN COUNTRY ANTENNE DIRECT:https://stream.antenne.de/country-antenne/stream/aacp
aby-classic-rock-live|ANTENNE BAYERN Classic Rock DIRECT:https://stream.antenne.de/classic-rock-live/stream/aacp
aby-coffee|ANTENNE BAYERN Coffee Music DIRECT:https://stream.antenne.de/coffee/stream/aacp
aby-dance-xxl|ANTENNE BAYERN Dance XXL DIRECT:https://stream.antenne.de/dance-xxl/stream/aacp
aby-deutsch-pop|ANTENNE BAYERN Deutsch Pop DIRECT:https://stream.antenne.de/deutsch-pop/stream/aacp
aby-faschings-hits|ANTENNE BAYERN Faschings Hits DIRECT:https://stream.antenne.de/faschings-hits/stream/aacp
aby-fresh|ANTENNE BAYERN Fresh DIRECT:https://stream.antenne.de/fresh/stream/aacp
aby-fruehlings-hits|ANTENNE BAYERN Frühlings Hits DIRECT:https://stream.antenne.de/fruehlings-hits/stream/aacp
aby-greatest-hits|ANTENNE BAYERN Greatest Hits DIRECT:https://stream.antenne.de/greatest-hits/stream/aacp
aby-event|ANTENNE BAYERN Grill Hits DIRECT:https://stream.antenne.de/event/stream/aacp
aby-halli-galli-gaudi|ANTENNE BAYERN Halli Galli Gaudi DIRECT:https://stream.antenne.de/halli-galli-gaudi/stream/aacp
aby-happy-hits|ANTENNE BAYERN Happy Hits DIRECT:https://stream.antenne.de/happy-hits/stream/aacp
aby-herbst-hits|ANTENNE BAYERN Herbst Hits DIRECT:https://stream.antenne.de/herbst-hits/stream/aacp
aby-hits-fuer-kids|ANTENNE BAYERN Hits für Kids DIRECT:https://stream.antenne.de/hits-fuer-kids/stream/aacp
aby-in-the-mix|ANTENNE BAYERN In the mix DIRECT:https://stream.antenne.de/in-the-mix/stream/aacp
aby-antenne-bayern-italo-hits|ANTENNE BAYERN Italo Hits DIRECT:https://stream.antenne.de/antenne-bayern-italo-hits/stream/aacp
aby-lounge|ANTENNE BAYERN Lounge DIRECT:https://stream.antenne.de/lounge/stream/aacp
aby-lovesongs|ANTENNE BAYERN Lovesongs DIRECT:https://stream.antenne.de/lovesongs/stream/aacp
aby-mallorca-party|ANTENNE BAYERN Mallorca Party DIRECT:https://stream.antenne.de/mallorca-party/stream/aacp
aby-antenne-bayern-ndw|ANTENNE BAYERN NDW DIRECT:https://stream.antenne.de/antenne-bayern-ndw/stream/aacp
aby-nur-die-musik|ANTENNE BAYERN Nur die Musik DIRECT:https://stream.antenne.de/nur-die-musik/stream/aacp
aby-oldie-antenne|ANTENNE BAYERN OLDIE ANTENNE Live - 60er, 70er, 80er DIRECT:https://stream.antenne.de/oldie-antenne/stream/aacp
aby-oktoberfest-hits|ANTENNE BAYERN Oktoberfest Hits DIRECT:https://stream.antenne.de/oktoberfest-hits/stream/aacp
aby-party-hits|ANTENNE BAYERN Party Hits DIRECT:https://stream.antenne.de/party-hits/stream/aacp
aby-pop-xxl|ANTENNE BAYERN Pop XXL DIRECT:https://stream.antenne.de/pop-xxl/stream/aacp
aby-rockantenne-bayern|ANTENNE BAYERN ROCK ANTENNE Bayern DIRECT:https://stream.antenne.de/rockantenne-bayern/stream/aacp
aby-relax|ANTENNE BAYERN Relax DIRECT:https://stream.antenne.de/relax/stream/aacp
aby-das-schlager-karussell|ANTENNE BAYERN Schlagersahne DIRECT:https://stream.antenne.de/das-schlager-karussell/stream/aacp
aby-sommer-hits|ANTENNE BAYERN Sommer Hits DIRECT:https://stream.antenne.de/sommer-hits/stream/aacp
aby-top-1000|ANTENNE BAYERN Top 1000 DIRECT:https://stream.antenne.de/top-1000/stream/aacp
aby-top-40|ANTENNE BAYERN Top 40 DIRECT:https://stream.antenne.de/top-40/stream/aacp
aby-weihnachts-hits|ANTENNE BAYERN Weihnachtshits DIRECT:https://stream.antenne.de/weihnachts-hits/stream/aacp
aby-workout-hits|ANTENNE BAYERN Workout Mix DIRECT:https://stream.antenne.de/workout-hits/stream/aacp
bassdrive http://bassdrive.com/v2/streams/BassDrive.pls
cvgm DIRECT:http://slacker.cvgm.net/cvgm192.ogg
dfmw|detektorfm-wort https://detektor.fm/detektor_fm-wort.m3u
dfmm|detektorfm-musik https://detektor.fm/detektor_fm-musik.m3u
dlf|deutschlandfunk OGGDEMUX:http://www.dradio.de/streaming/dlf_hq_ogg.m3u
dradiowissen OGGDEMUX:http://www.dradio.de/streaming/dradiowissen_hq_ogg.m3u
klassikbrazil DIRECT:http://stream.klassikradio.de/brazil/mp3-128/www.klassikradio.de/
klassikdreams DIRECT:http://stream.klassikradio.de/dreams/mp3-128/www.klassikradio.de/
klassikgames DIRECT:http://stream.klassikradio.de/games/mp3-128/www.klassikradio.de/
klassikhealing DIRECT:http://stream.klassikradio.de/healing/mp3-128/www.klassikradio.de/
klassiklegenden DIRECT:http://stream.klassikradio.de/legenden/mp3-128/www.klassikradio.de/
klassiklive DIRECT:http://stream.klassikradio.de/live/mp3-128/www.klassikradio.de/
klassiklounge DIRECT:http://stream.klassikradio.de/lounge/mp3-128/www.klassikradio.de/
klassikloungebeat DIRECT:http://stream.klassikradio.de/loungebeat/mp3-128/www.klassikradio.de/
klassikmovie DIRECT:http://stream.klassikradio.de/movie/mp3-128/www.klassikradio.de/
klassiknature DIRECT:http://stream.klassikradio.de/nature/mp3-128/www.klassikradio.de/
klassikpiano DIRECT:http://stream.klassikradio.de/piano/mp3-128/www.klassikradio.de/
klassikrock DIRECT:http://stream.klassikradio.de/rock/mp3-128/www.klassikradio.de/
klassikschiller DIRECT:http://stream.klassikradio.de/schiller/mp3-128/www.klassikradio.de/
kohina OGGDEMUX:https://kohina.duckdns.org/playlist_https.m3u
ndr2 http://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u
nectarine DIRECT:http://nectarine.shakeme.info:8000/nectarine
nubreaks http://nubreaks.com/modules/mod_internetradio/makeplaylist.php?ip=69.175.103.232&port=8700&format=PLS
rainwave http://all.rainwave.cc/tune_in/5.ogg
ocremix http://ocr.rainwave.cc/tune_in/2.ogg
sid|sid station http://185.80.220.12:2199/tunein/jotayl00.pls
slay|slayradio DIRECT:http://relay1.slayradio.org:8000/
soma-70s https://somafm.com/seventies.pls
soma-7soul https://somafm.com/startstream=7soul.pls
soma-bagel https://somafm.com/startstream=bagel.pls
soma-beatblender https://somafm.com/startstream=beatblender.pls
soma-brfm https://somafm.com/startstream=brfm.pls
soma-bootliquor https://somafm.com/startstream=bootliquor.pls
soma-brfm https://somafm.com/brfm.pls
soma-cliqhop https://somafm.com/startstream=cliqhop.pls
soma-covers https://somafm.com/startstream=covers.pls
soma-christmas-lounge https://somafm.com/startstream=christmas.pls
soma-defcon https://somafm.com/startstream=defcon.pls
soma-digitalis https://somafm.com/startstream=digitalis.pls
drone|soma-dronezone https://somafm.com/startstream=dronezone.pls
soma-dubstep https://somafm.com/startstream=dubstep.pls
soma-fluid https://somafm.com/fluid.pls
soma-folkfwd https://somafm.com/folkfwd.pls
soma-groovesalad https://somafm.com/startstream=groovesalad.pls
soma-gsclassic https://somafm.com/startstream=gsclassic.pls
some-jollysoul https://somafm.com/startstream=jollysoul.pls
soma-illstreet https://somafm.com/startstream=illstreet.pls
ip|soma-indiepop https://somafm.com/startstream=indiepop.pls
soma-live https://somafm.com/startstream=live.pls
soma-lush https://somafm.com/startstream=lush.pls
soma-metal https://somafm.com/metal.pls
mc|soma-missioncontrol https://somafm.com/startstream=missioncontrol.pls
soma-poptron https://somafm.com/startstream=poptron.pls
sa|soma-secretagent https://somafm.com/startstream=secretagent.pls
soma-sf1033 https://somafm.com/sf1033.pls
soma-specials https://somafm.com/specials.pls
soma-sonicuniverse https://somafm.com/startstream=sonicuniverse.pls
soma-spacestation https://somafm.com/startstream=spacestation.pls
soma-suburbsofgoa https://somafm.com/startstream=suburbsofgoa.pls
soma-tags https://somafm.com/startstream=tags.pls
soma-thistle https://somafm.com/thistle.pls
soma-u80s https://somafm.com/startstream=u80s.pls
soma-xmasinfrisko https://somafm.com/startstream=xmasinfrisko.pls
soma-xmasrocks https://somafm.com/startstream=xmasrocks.pls
sst|streaming soundtracks http://www.streamingsoundtracks.com/modules/Listen/MP3-hi.pls
ctfm|ClubTime.FM http://listen.clubtime.fm/dsl.pls
wdr2|WDR 2 http://www.wdr.de/wdrlive/media/mp3/wdr2-muensterland.m3u
htfm|HouseTime.FM http://listen.housetime.fm/dsl.pls
tbfm|TranceBase.FM http://listen.trancebase.fm/dsl.pls
Techno.FM Live Channel DIRECT:https://stream.techno.fm/radio1-192k.mp3
ssl|sunshine live DIRECT:https://stream.sunshine-live.de/live/mp3-192
ssl-ch|sunshine live - Schweiz DIRECT:https://stream.sunshine-live.de/schweiz/mp3-192
ssl-ecafe|sunshine live - Électrique Café DIRECT:https://stream.sunshine-live.de/electriquecafe/mp3-192
ssl-eurodance|sunshine live - Eurodance DIRECT:https://stream.sunshine-live.de/eurodance/mp3-192
ssl-mayday|sunshine live - Mayday DIRECT:https://stream.sunshine-live.de/mayday/mp3-192
ssl-natureone|sunshine live - Nature One DIRECT:https://stream.sunshine-live.de/natureone/mp3-192
ssl-timewarp|sunshine live - Time Warp DIRECT:https://stream.sunshine-live.de/timewarp/mp3-192
ssl-80s|sunshine live - 80s DIRECT:https://stream.sunshine-live.de/80er/mp3-192
ssl-90s|sunshine live - 90s DIRECT:https://stream.sunshine-live.de/90er/mp3-192
ssl-2000s|sunshine live - 2000s DIRECT:https://stream.sunshine-live.de/2000er/mp3-192
ssl-2010s|sunshine live - 2010s DIRECT:https://stream.sunshine-live.de/2010er/mp3-192
ssl-chillout|sunshine live - Chillout DIRECT:https://stream.sunshine-live.de/sp8/mp3-192
ssl-classics|sunshine live - Classics DIRECT:https://stream.sunshine-live.de/classics/mp3-192
ssl-edm|sunshine live - EDM DIRECT:https://stream.sunshine-live.de/edm/mp3-192
ssl-femalepower|sunshine live - Female Power DIRECT:https://stream.sunshine-live.de/technoqueens/mp3-192
ssl-festival|sunshine live - Festival DIRECT:https://stream.sunshine-live.de/festival/mp3-192
ssl-hardstyle|sunshine live - Hardstyle DIRECT:https://stream.sunshine-live.de/hardstyle/mp3-192
ssl-hardcore|sunshine live - Hardcore DIRECT:https://stream.sunshine-live.de/Hardcore/mp3-192
ssl-hardtechno|sunshine live - Hardtechno DIRECT:https://stream.sunshine-live.de/Hardtechno/mp3-192
ssl-house|sunshine live - House DIRECT:https://stream.sunshine-live.de/house/mp3-192
ssl-afrohouse|sunshine live - Afro House DIRECT:https://stream.sunshine-live.de/afrohouse/mp3-192
ssl-ibiza|sunshine live - Ibiza DIRECT:https://stream.sunshine-live.de/ibiza/mp3-192
ssl-lounge|sunshine live - Lounge DIRECT:https://stream.sunshine-live.de/lounge/mp3-192
ssl-melodicbeats|sunshine live - Melodic Beats DIRECT:https://stream.sunshine-live.de/MelodicB/mp3-192
ssl-mixmission|sunshine live - Mix Mission DIRECT:https://stream.sunshine-live.de/mixmission/mp3-192
ssl-techno|sunshine live - Techno DIRECT:https://stream.sunshine-live.de/techno/mp3-192
ssl-trance|sunshine live - Trance DIRECT:https://stream.sunshine-live.de/trance/mp3-192
ssl-workout|sunshine live - Workout DIRECT:https://stream.sunshine-live.de/workout/mp3-192
ssl-blue|sunshine live - Blue DIRECT:https://stream.sunshine-live.de/Blue/mp3-192

# bitjam DIRECT:OGGDEMUX:http://88.80.10.21:8086/bitjam.ogg
# cryosleep http://207.200.96.225:8022/listen.pls
# hardrave.jp http://hardrave.jp:9000/listen.pls
# phish|live Phish radio http://www.livephish.com/radio/listen.m3u
# rivendell http://www.radiorivendell.com/lib/blocks/rr_play.php?play_f=play&bitrate=128&codec=mp3&player=Winamp
# ssl|sunshine live http://lsd.newmedia.tiscali-business.com/bb/redirect.lsc?adid=0&content=live&media=mp3&stream=sunshinelive/livestream.mp3
# subpop OGGDEMUX:DIRECT:http://pushnpop.net:8912/subpop.ogg
# tt24|Turntables24.com http://stream.turntables24.de:9200/listen.pls
# r7|radioseven http://www.radioseven.se/128.pls
# ttfm|Techno.Techno.FM DIRECT:http://stream.techno.fm/techno.256k.mp3
# ltfm|Live.Techno.FM DIRECT:http://stream.techno.fm/live.256k.mp3
# soma-doomed https://somafm.com/startstream=doomed.pls
