---
name: build
on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '14 18 23 * *'

jobs:
  test-only:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: ['5.38', '5.36', '5.30']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: ./test.sh --offline
